# ruff.toml
line-length = 120
target-version = "py312"

[lint]
select = ["E", "F", "I"]     # errors, flakes, import sort
# Je kunt E501 negeren wanneer je de formatter gebruikt:
# extend-ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
